window.REAL_STUDENT_DB = [
    {
        "no": 1,
        "student_id": "19168",
        "photo_url": "photos/19168.jpg",
        "title": "เด็กชาย",
        "firstname": "กฤตษณุ",
        "lastname": "โปทาอุด",
        "fullname": "เด็กชายกฤตษณุ โปทาอุด",
        "fullname_en": "Kritsanu Pothaud",
        "nickname": "ขันโตก",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1101000475589",
        "birthdate": "14 กุมภาพันธ์ 2557",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0643476813",
        "school_old": "โรงเรียนอนุบาลเมืองเชียงราย (สันทรายราษฎร์ดรุณานุเคราะห์)",
        "gpa": "3.81",
        "dream": "ครูพละ",
        "guardian_name": "นาง กฤษณา โปทาอุด",
        "guardian_phone": "0844696787",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 14,
            "math_basic": 17,
            "thai": 9,
            "math_add1": 18,
            "math_add2": 3,
            "chinese": 15,
            "eng_basic": 16,
            "sci_basic": 15,
            "eng_rw": 13,
            "total_score": 136
        }
    },
    {
        "no": 2,
        "student_id": "19169",
        "photo_url": "photos/19169.jpg",
        "title": "เด็กชาย",
        "firstname": "กฤติกร",
        "lastname": "สุวรรณ์",
        "fullname": "เด็กชายกฤติกร สุวรรณ์",
        "fullname_en": "Krittikorn Suwan",
        "nickname": "โอดิน",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901623760",
        "birthdate": "7 พฤศจิกายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0809277716",
        "school_old": "โรงเรียนศิริมาตย์เทวี",
        "gpa": "3.38",
        "dream": "วิศวะ",
        "guardian_name": "นาย ราชันย์ สุวรรณ์",
        "guardian_phone": "0882519234",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 15,
            "social": 12,
            "math_basic": 17,
            "thai": 13,
            "math_add1": 18,
            "math_add2": 4,
            "chinese": 14,
            "eng_basic": 15,
            "sci_basic": 16,
            "eng_rw": 11,
            "total_score": 135
        }
    },
    {
        "no": 3,
        "student_id": "19170",
        "photo_url": "photos/19170.jpg",
        "title": "เด็กชาย",
        "firstname": "กฤษณพล",
        "lastname": "กองห่อ",
        "fullname": "เด็กชายกฤษณพล กองห่อ",
        "fullname_en": "KRITSANAPON KONGHOR",
        "nickname": "ภูมิใจ",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1509967000621",
        "birthdate": "22 สิงหาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0988789174",
        "school_old": "โรงเรียนเทศบาล 7 ฝั่งหมิ่น",
        "gpa": "3.3",
        "dream": "สตรีมเมอร์",
        "guardian_name": "นางสาว วรฤทัย ประมาณ",
        "guardian_phone": "0622481771",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 11,
            "social": 11,
            "math_basic": 13,
            "thai": 11,
            "math_add1": 10,
            "math_add2": 3,
            "chinese": 13,
            "eng_basic": 10,
            "sci_basic": 11,
            "eng_rw": 8,
            "total_score": 101
        }
    },
    {
        "no": 4,
        "student_id": "19172",
        "photo_url": "photos/19172.jpg",
        "title": "เด็กชาย",
        "firstname": "คุณภัทร",
        "lastname": "ยัง",
        "fullname": "เด็กชายคุณภัทร ยัง",
        "fullname_en": "Khunnapat Yang",
        "nickname": "เบนนี่",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1101700555411",
        "birthdate": "5 มกราคม 2557",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0821617066",
        "school_old": "โรงเรียนมาร์รีรักษ์",
        "gpa": "3.87",
        "dream": "สัตวแพทย์",
        "guardian_name": "นางสาว ชุติมา วงค์แก้ว",
        "guardian_phone": "0813756406",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 17,
            "social": 16,
            "math_basic": 7,
            "thai": 12,
            "math_add1": 13,
            "math_add2": 1,
            "chinese": 15,
            "eng_basic": 17,
            "sci_basic": 11,
            "eng_rw": 18,
            "total_score": 127
        }
    },
    {
        "no": 5,
        "student_id": "19173",
        "photo_url": "photos/19173.jpg",
        "title": "เด็กชาย",
        "firstname": "จารุภัทร",
        "lastname": "รัตนอมรวิสิทธิ์",
        "fullname": "เด็กชายจารุภัทร รัตนอมรวิสิทธิ์",
        "fullname_en": "Jarupat Rattanaamornvisith",
        "nickname": "เอิร์ธ",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901618898",
        "birthdate": "13 ตุลาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0983067175",
        "school_old": "โรงเรียนเทศบาล 7 ฝั่งหมิ่น",
        "gpa": "3.57",
        "dream": "หมอ",
        "guardian_name": "นาย พีรวิชญ์ รัตนอมรวิสิทธิ์",
        "guardian_phone": "0895598908",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 8,
            "social": 11,
            "math_basic": 5,
            "thai": 8,
            "math_add1": 4,
            "math_add2": 1,
            "chinese": 14,
            "eng_basic": 11,
            "sci_basic": 8,
            "eng_rw": 12,
            "total_score": 82
        }
    },
    {
        "no": 6,
        "student_id": "19174",
        "photo_url": "photos/19174.jpg",
        "title": "เด็กชาย",
        "firstname": "ชยณัฐ",
        "lastname": "เทพวงค์",
        "fullname": "เด็กชายชยณัฐ เทพวงค์",
        "fullname_en": "Chayanat Thepwong",
        "nickname": "พอตเตอร์",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901623743",
        "birthdate": "7 พฤศจิกายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0858199991",
        "school_old": "โรงเรียนอนุบาลแม่สรวย",
        "gpa": "3.81",
        "dream": "ตำรวจ",
        "guardian_name": "นางสาว ผกามาศ ฉายปิติศิริ",
        "guardian_phone": "095454587",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 12,
            "math_basic": 12,
            "thai": 11,
            "math_add1": 6,
            "math_add2": 2,
            "chinese": 14,
            "eng_basic": 15,
            "sci_basic": 12,
            "eng_rw": 13,
            "total_score": 113
        }
    },
    {
        "no": 7,
        "student_id": "19175",
        "photo_url": "photos/19175.jpg",
        "title": "เด็กชาย",
        "firstname": "ณวัฒน์",
        "lastname": "คำเครื่อง",
        "fullname": "เด็กชายณวัฒน์ คำเครื่อง",
        "fullname_en": "Nawat Comekruang",
        "nickname": "ผักไผ่",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901630936",
        "birthdate": "16 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0813870561",
        "school_old": "โรงเรียนเทศบาล 1 ศรีเกิด",
        "gpa": "3.78",
        "dream": "ครู",
        "guardian_name": "นาย นายอุเทน คำเครื่อง",
        "guardian_phone": "0956877513",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม B",
        "ls_status": "เด็กกลุ่มห่วงใย (LS)",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 15,
            "math_basic": 15,
            "thai": 13,
            "math_add1": 11,
            "math_add2": 2,
            "chinese": 17,
            "eng_basic": 11,
            "sci_basic": 7,
            "eng_rw": 13,
            "total_score": 120
        }
    },
    {
        "no": 8,
        "student_id": "19176",
        "photo_url": "photos/19176.jpg",
        "title": "เด็กชาย",
        "firstname": "ปวรุตม์",
        "lastname": "คันธะ",
        "fullname": "เด็กชายปวรุตม์ คันธะ",
        "fullname_en": "Pawarut Kantha",
        "nickname": "อังเปา",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901611036",
        "birthdate": "1 กันยายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0968050893, 0893005859",
        "school_old": "โรงเรียนอนุบาลเชียงราย",
        "gpa": "3.03",
        "dream": "วิศวกร",
        "guardian_name": "นาง อมรรัตน์ คันธะ",
        "guardian_phone": "0948299902",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 11,
            "social": 12,
            "math_basic": 14,
            "thai": 7,
            "math_add1": 7,
            "math_add2": 2,
            "chinese": 17,
            "eng_basic": 11,
            "sci_basic": 7,
            "eng_rw": 8,
            "total_score": 96
        }
    },
    {
        "no": 9,
        "student_id": "19177",
        "photo_url": "photos/19177.jpg",
        "title": "เด็กชาย",
        "firstname": "พชรพล",
        "lastname": "สุ่มใจยา",
        "fullname": "เด็กชายพชรพล สุ่มใจยา",
        "fullname_en": "Pacharaphon Sumjaiya",
        "nickname": "เกื้อ",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901621236",
        "birthdate": "22 ตุลาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0629514389",
        "school_old": "โรงเรียนบุญพิทักษ์วิทยา",
        "gpa": "3.14",
        "dream": "ดีไซเนอร์",
        "guardian_name": "นาย อรรถพล สุ่มใจยา",
        "guardian_phone": "0815307733",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 14,
            "social": 14,
            "math_basic": 9,
            "thai": 11,
            "math_add1": 6,
            "math_add2": 2,
            "chinese": 14,
            "eng_basic": 13,
            "sci_basic": 7,
            "eng_rw": 9,
            "total_score": 99
        }
    },
    {
        "no": 10,
        "student_id": "19178",
        "photo_url": "photos/19178.jpg",
        "title": "เด็กชาย",
        "firstname": "ภานุวัฒน์",
        "lastname": "บุษดี",
        "fullname": "เด็กชายภานุวัฒน์ บุษดี",
        "fullname_en": "Panuwat Butsadee",
        "nickname": "การ์ฟิว",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1429900847967",
        "birthdate": "20 พฤษภาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0936173158",
        "school_old": "โรงเรียนเทศบาล 3 ศรีทรายมูล",
        "gpa": "3.46",
        "dream": "หมอ",
        "guardian_name": "นางสาว วราภรณ์ สุโขยะชัย",
        "guardian_phone": "0861949764",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 8,
            "social": 14,
            "math_basic": 11,
            "thai": 12,
            "math_add1": 5,
            "math_add2": 1,
            "chinese": 14,
            "eng_basic": 12,
            "sci_basic": 11,
            "eng_rw": 11,
            "total_score": 99
        }
    },
    {
        "no": 11,
        "student_id": "19179",
        "photo_url": "photos/19179.jpg",
        "title": "เด็กชาย",
        "firstname": "ภูมิพัฒน์",
        "lastname": "แสนทนงศักดิ์",
        "fullname": "เด็กชายภูมิพัฒน์ แสนทนงศักดิ์",
        "fullname_en": "Phumiphat Santanongsak",
        "nickname": "อาตี้",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901612164",
        "birthdate": "6 กันยายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0644673999",
        "school_old": "โรงเรียนเทศบาล 2 หนองบัว",
        "gpa": "3.44",
        "dream": "สืบสวน สอบสวน",
        "guardian_name": "นาง พัชรีพร แสนทนงศักดิ์",
        "guardian_phone": "0841710498",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 6,
            "social": 10,
            "math_basic": 12,
            "thai": 7,
            "math_add1": 10,
            "math_add2": 3,
            "chinese": 14,
            "eng_basic": 7,
            "sci_basic": 11,
            "eng_rw": 3,
            "total_score": 83
        }
    },
    {
        "no": 12,
        "student_id": "19180",
        "photo_url": "photos/19180.jpg",
        "title": "เด็กชาย",
        "firstname": "วรานนท์",
        "lastname": "ใจกุศลดำรง",
        "fullname": "เด็กชายวรานนท์ ใจกุศลดำรง",
        "fullname_en": "Waranon Chaikusondamrong",
        "nickname": "หนึ่ง",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901622771",
        "birthdate": "1 พฤศจิกายน 2556",
        "religion": "ศาสนาคริสต์",
        "student_phone": "0924941986",
        "school_old": "โรงเรียนบ้านขาแหย่งพัฒนา",
        "gpa": "3.6",
        "dream": "ช่างยนต์",
        "guardian_name": "นาย วีรพงษ์ ใจกุศลดำรง",
        "guardian_phone": "0898536721",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 12,
            "social": 13,
            "math_basic": 12,
            "thai": 14,
            "math_add1": 9,
            "math_add2": 3,
            "chinese": 14,
            "eng_basic": 13,
            "sci_basic": 11,
            "eng_rw": 10,
            "total_score": 111
        }
    },
    {
        "no": 13,
        "student_id": "19181",
        "photo_url": "photos/19181.jpg",
        "title": "เด็กชาย",
        "firstname": "วสุธร",
        "lastname": "มหาวัน",
        "fullname": "เด็กชายวสุธร มหาวัน",
        "fullname_en": "WASUTHON MAHAWAN",
        "nickname": "ออมตังค์",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901621902",
        "birthdate": "23 ตุลาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0958576412",
        "school_old": "โรงเรียนศิริมาตย์เทวี",
        "gpa": "3.15",
        "dream": "-",
        "guardian_name": "นายวทัญญา มหาวัน นายวทัญญา มหาวัน",
        "guardian_phone": "0861800034",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 15,
            "social": 11,
            "math_basic": 12,
            "thai": 11,
            "math_add1": 12,
            "math_add2": 4,
            "chinese": 12,
            "eng_basic": 14,
            "sci_basic": 11,
            "eng_rw": 13,
            "total_score": 115
        }
    },
    {
        "no": 14,
        "student_id": "19182",
        "photo_url": "photos/19182.jpg",
        "title": "เด็กชาย",
        "firstname": "ศุภากร",
        "lastname": "รวมจิตต์",
        "fullname": "เด็กชายศุภากร รวมจิตต์",
        "fullname_en": "Suphakorn Ruamchit",
        "nickname": "นีโอ",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901598005",
        "birthdate": "13 มิถุนายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0648636681",
        "school_old": "โรงเรียนสาธิตมหาวิทยาลัยราชภัฏเชียงราย",
        "gpa": "3.86",
        "dream": "ข้าราชการครู",
        "guardian_name": "นางสาว รมิภา รวมจิตต์",
        "guardian_phone": "0821931955",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม C",
        "ls_status": "เด็กกลุ่มห่วงใย (LS)",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 15,
            "social": 12,
            "math_basic": 18,
            "thai": 12,
            "math_add1": 15,
            "math_add2": 5,
            "chinese": 17,
            "eng_basic": 13,
            "sci_basic": 14,
            "eng_rw": 15,
            "total_score": 136
        }
    },
    {
        "no": 15,
        "student_id": "19183",
        "photo_url": "photos/19183.jpg",
        "title": "เด็กชาย",
        "firstname": "อรรถพันธ์",
        "lastname": "ตาสาย",
        "fullname": "เด็กชายอรรถพันธ์ ตาสาย",
        "fullname_en": "Oatthaphan Tasai",
        "nickname": "ภูริ",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1570800162327",
        "birthdate": "08 สิงหาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0612202695",
        "school_old": "โรงเรียนบ้านทับกุมารทอง",
        "gpa": "3.87",
        "dream": "วิศวะ",
        "guardian_name": "นางสาว อริสา คำแสน",
        "guardian_phone": "0969832986",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 9,
            "social": 13,
            "math_basic": 14,
            "thai": 9,
            "math_add1": 16,
            "math_add2": 4,
            "chinese": 11,
            "eng_basic": 10,
            "sci_basic": 14,
            "eng_rw": 5,
            "total_score": 105
        }
    },
    {
        "no": 16,
        "student_id": "19184",
        "photo_url": "photos/19184.jpg",
        "title": "เด็กชาย",
        "firstname": "อัฟฟานคาน",
        "lastname": "อนุรักษ์",
        "fullname": "เด็กชายอัฟฟานคาน อนุรักษ์",
        "fullname_en": "Affankhan Anurak",
        "nickname": "อัฟฟาน",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901596487",
        "birthdate": "3 มิถุนายน 2556",
        "religion": "ศาสนาอิสลาม",
        "student_phone": "0910718219",
        "school_old": "โรงเรียนมารีย์รักษ์เชียงราย",
        "gpa": "3.86",
        "dream": "ทันตแพทย์",
        "guardian_name": "นางสาว หนึ่งฤทัย อนุรักษ์",
        "guardian_phone": "0835700783",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 12,
            "math_basic": 11,
            "thai": 10,
            "math_add1": 8,
            "math_add2": 3,
            "chinese": 11,
            "eng_basic": 14,
            "sci_basic": 11,
            "eng_rw": 11,
            "total_score": 107
        }
    },
    {
        "no": 17,
        "student_id": "19185",
        "photo_url": "photos/19185.jpg",
        "title": "เด็กหญิง",
        "firstname": "กชกานต์",
        "lastname": "แสนคำลือ",
        "fullname": "เด็กหญิงกชกานต์ แสนคำลือ",
        "fullname_en": "Kotchakant Sankhamlue",
        "nickname": "เนปจูน",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901630251",
        "birthdate": "13 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0972027693",
        "school_old": "โรงเรียนสาธิตมหาวิทยาลัยราชภัฏเชียงราย",
        "gpa": "3.78",
        "dream": "เชฟ",
        "guardian_name": "นางสาว ชัชฎาภา วรโชติวนาไพร",
        "guardian_phone": "0861149787",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 14,
            "social": 12,
            "math_basic": 13,
            "thai": 11,
            "math_add1": 11,
            "math_add2": 2,
            "chinese": 15,
            "eng_basic": 15,
            "sci_basic": 9,
            "eng_rw": 11,
            "total_score": 113
        }
    },
    {
        "no": 18,
        "student_id": "19186",
        "photo_url": "photos/19186.jpg",
        "title": "เด็กหญิง",
        "firstname": "กชพรรณ",
        "lastname": "กองแสง",
        "fullname": "เด็กหญิงกชพรรณ กองแสง",
        "fullname_en": "Kotchaphan Kongsaeng",
        "nickname": "ชะเอม",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901598552",
        "birthdate": "17 มิถุนายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0639345361",
        "school_old": "โรงเรียนวัฒนศึกษา",
        "gpa": "3.76",
        "dream": "อยากเป็นศิลปิน😆",
        "guardian_name": "น.ส.กาญจนิต กองแสง น.ส.กาญจนิต  กองแสง",
        "guardian_phone": "0826981615",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 14,
            "math_basic": 17,
            "thai": 13,
            "math_add1": 19,
            "math_add2": 4,
            "chinese": 18,
            "eng_basic": 16,
            "sci_basic": 13,
            "eng_rw": 13,
            "total_score": 143
        }
    },
    {
        "no": 19,
        "student_id": "19187",
        "photo_url": "photos/19187.jpg",
        "title": "เด็กหญิง",
        "firstname": "ชลธิชา",
        "lastname": "แซตูกู",
        "fullname": "เด็กหญิงชลธิชา แซตูกู",
        "fullname_en": "Chonthicha  Saetookoo",
        "nickname": "มีน",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901612792",
        "birthdate": "10 กันยายน 2556",
        "religion": "ศาสนาคริสต์",
        "student_phone": "0813536420",
        "school_old": "โรงเรียนเทศบาล 1 ป่าก่อดำ",
        "gpa": "3.68",
        "dream": "ทันตแพทย์",
        "guardian_name": "นาย นาย นพดล แซตูกู",
        "guardian_phone": "0967097950",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 13,
            "social": 13,
            "math_basic": 11,
            "thai": 14,
            "math_add1": 12,
            "math_add2": 4,
            "chinese": 17,
            "eng_basic": 16,
            "sci_basic": 15,
            "eng_rw": 8,
            "total_score": 123
        }
    },
    {
        "no": 20,
        "student_id": "19188",
        "photo_url": "photos/19188.jpg",
        "title": "เด็กหญิง",
        "firstname": "ฌานณิชา",
        "lastname": "จารุชัยกุล",
        "fullname": "เด็กหญิงฌานณิชา จารุชัยกุล",
        "fullname_en": "Channicha  Jaruchaikul",
        "nickname": "เฌอ",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901673970",
        "birthdate": "31 สิงหาคม 2557",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0837920987",
        "school_old": "โรงเรียนเชียงแสนอาคาเดมี",
        "gpa": "3.74",
        "dream": "หมอฟัน",
        "guardian_name": "นางสาว พัชรีย์ คงธะ",
        "guardian_phone": "0945361167",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 13,
            "math_basic": 15,
            "thai": 9,
            "math_add1": 12,
            "math_add2": 3,
            "chinese": 18,
            "eng_basic": 13,
            "sci_basic": 13,
            "eng_rw": 10,
            "total_score": 122
        }
    },
    {
        "no": 21,
        "student_id": "19189",
        "photo_url": "photos/19189.jpg",
        "title": "เด็กหญิง",
        "firstname": "ญาณวิภา",
        "lastname": "วงค์แสนสี",
        "fullname": "เด็กหญิงญาณวิภา วงค์แสนสี",
        "fullname_en": "YANAWIPHA WONGSAENSEE",
        "nickname": "พลอย",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901602380",
        "birthdate": "11 กรกฎาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0613487677",
        "school_old": "โรงเรียนอนุบาลพญาเม็งราย",
        "gpa": "3.77",
        "dream": "ครู",
        "guardian_name": "นางสาว อนุธิดา พานิชย์",
        "guardian_phone": "0892092714",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม A",
        "ls_status": "เด็กกลุ่มห่วงใย (LS)",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 12,
            "social": 9,
            "math_basic": 10,
            "thai": 11,
            "math_add1": 4,
            "math_add2": 1,
            "chinese": 13,
            "eng_basic": 8,
            "sci_basic": 11,
            "eng_rw": 9,
            "total_score": 88
        }
    },
    {
        "no": 22,
        "student_id": "19190",
        "photo_url": "photos/19190.jpg",
        "title": "เด็กหญิง",
        "firstname": "ณัฏฐรียา",
        "lastname": "วงค์พิบูลย์",
        "fullname": "เด็กหญิงณัฏฐรียา วงค์พิบูลย์",
        "fullname_en": "Natthareeya Wongphiboon",
        "nickname": "แพรไหม",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1839902326651",
        "birthdate": "03 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "066-023-2462",
        "school_old": "โรงเรียนสาธิตมหาวิทยาลัยราชภัฏเชียงราย",
        "gpa": "3.87",
        "dream": "-",
        "guardian_name": "นาย พยงค์ วงค์พิบูลย์",
        "guardian_phone": "0628952462",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 17,
            "social": 12,
            "math_basic": 14,
            "thai": 12,
            "math_add1": 17,
            "math_add2": 4,
            "chinese": 17,
            "eng_basic": 17,
            "sci_basic": 17,
            "eng_rw": 15,
            "total_score": 142
        }
    },
    {
        "no": 23,
        "student_id": "19191",
        "photo_url": "photos/19191.jpg",
        "title": "เด็กหญิง",
        "firstname": "ณัฐฐริณีย์",
        "lastname": "เผือกนอก",
        "fullname": "เด็กหญิงณัฐฐริณีย์ เผือกนอก",
        "fullname_en": "NUTTARINEE PUEAKNOK",
        "nickname": "ขิม",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901614701",
        "birthdate": "18 กันยายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0656461607",
        "school_old": "โรงเรียนมารีย์รักษ์เชียงราย(แผนกประถม)",
        "gpa": "3.99",
        "dream": "นักแบดมินตัน",
        "guardian_name": "นาง มัทนา เผือกนอก",
        "guardian_phone": "0985958177",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 19,
            "social": 11,
            "math_basic": 14,
            "thai": 11,
            "math_add1": 12,
            "math_add2": 3,
            "chinese": 16,
            "eng_basic": 18,
            "sci_basic": 13,
            "eng_rw": 17,
            "total_score": 134
        }
    },
    {
        "no": 24,
        "student_id": "19192",
        "photo_url": "photos/19192.jpg",
        "title": "เด็กหญิง",
        "firstname": "ณัฐธิดา",
        "lastname": "บุรีนอก",
        "fullname": "เด็กหญิงณัฐธิดา บุรีนอก",
        "fullname_en": "Natthida Burenok",
        "nickname": "นาเนียร์",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1570200131935",
        "birthdate": "25 กรกฎาคม 2556",
        "religion": "ศาสนาคริสต์",
        "student_phone": "0807143411",
        "school_old": "โรงเรียนอนุบาลเวียงชัย",
        "gpa": "3.65",
        "dream": "ตำรวจ",
        "guardian_name": "นางสาว อนุชตรา บุรีนอก",
        "guardian_phone": "0984822237",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 12,
            "social": 10,
            "math_basic": 7,
            "thai": 11,
            "math_add1": 10,
            "math_add2": 3,
            "chinese": 11,
            "eng_basic": 9,
            "sci_basic": 10,
            "eng_rw": 7,
            "total_score": 90
        }
    },
    {
        "no": 25,
        "student_id": "19193",
        "photo_url": "photos/19193.jpg",
        "title": "เด็กหญิง",
        "firstname": "ณิชารีย์",
        "lastname": "ธิแก้ว",
        "fullname": "เด็กหญิงณิชารีย์ ธิแก้ว",
        "fullname_en": "Nicharee Thikaew",
        "nickname": "ยิ้ม",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1570200131986",
        "birthdate": "4 สิงหาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0945508480",
        "school_old": "โรงเรียนอนุบาลเวียงชัย",
        "gpa": "3.95",
        "dream": "พยาบาล",
        "guardian_name": "นาย โกเมทร์ ธิแก้ว",
        "guardian_phone": "0829176468",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 13,
            "social": 13,
            "math_basic": 15,
            "thai": 15,
            "math_add1": 17,
            "math_add2": 2,
            "chinese": 13,
            "eng_basic": 16,
            "sci_basic": 13,
            "eng_rw": 7,
            "total_score": 124
        }
    },
    {
        "no": 26,
        "student_id": "19194",
        "photo_url": "photos/19194.jpg",
        "title": "เด็กหญิง",
        "firstname": "ดุลยา",
        "lastname": "เขื่อนแก้ว",
        "fullname": "เด็กหญิงดุลยา เขื่อนแก้ว",
        "fullname_en": "Dulaya Khyeankaew",
        "nickname": "น้ำหอม",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901645798",
        "birthdate": "15 มีนาคม 2557",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0969163531",
        "school_old": "โรงเรียนอนุบาลพญาเม็งราย",
        "gpa": "3.91",
        "dream": "นักวิทยาศาสตร์,หมอ",
        "guardian_name": "นาง จิตรานุช   เขื่อนแก้ว",
        "guardian_phone": "0823926472",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 12,
            "social": 12,
            "math_basic": 14,
            "thai": 10,
            "math_add1": 18,
            "math_add2": 4,
            "chinese": 15,
            "eng_basic": 15,
            "sci_basic": 13,
            "eng_rw": 10,
            "total_score": 123
        }
    },
    {
        "no": 27,
        "student_id": "19195",
        "photo_url": "photos/19195.jpg",
        "title": "เด็กชาย",
        "firstname": "ธนดล",
        "lastname": "ทาทอง",
        "fullname": "เด็กชายธนดล ทาทอง",
        "fullname_en": "Thanadon Thathong",
        "nickname": "เเสตมป์",
        "gender": "ชาย",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901619649",
        "birthdate": "16 ตุลาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0954462590",
        "school_old": "โรงเรียนบ้านเเม่จัน(เชียงเเสนประชานุสาสน์)",
        "gpa": "3.45",
        "dream": "หมอ",
        "guardian_name": "นาง ชลาลัย ทาทอง",
        "guardian_phone": "0819514322",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 11,
            "social": 11,
            "math_basic": 11,
            "thai": 9,
            "math_add1": 9,
            "math_add2": 1,
            "chinese": 10,
            "eng_basic": 9,
            "sci_basic": 13,
            "eng_rw": 5,
            "total_score": 89
        }
    },
    {
        "no": 28,
        "student_id": "19196",
        "photo_url": "photos/19196.jpg",
        "title": "เด็กหญิง",
        "firstname": "ธนัญชญา",
        "lastname": "สมแดง",
        "fullname": "เด็กหญิงธนัญชญา สมแดง",
        "fullname_en": "Thananchaya Somdang",
        "nickname": "วันดี",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901614906",
        "birthdate": "22 กันยายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0983543462",
        "school_old": "มารีย์รักษ์เชียงราย",
        "gpa": "3.88",
        "dream": "แพทย์",
        "guardian_name": "นาง ศศินันท์ สมแดง",
        "guardian_phone": "0879850463",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม B",
        "ls_status": "เด็กกลุ่มห่วงใย (LS)",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 18,
            "social": 13,
            "math_basic": 13,
            "thai": 11,
            "math_add1": 17,
            "math_add2": 4,
            "chinese": 15,
            "eng_basic": 17,
            "sci_basic": 14,
            "eng_rw": 17,
            "total_score": 139
        }
    },
    {
        "no": 29,
        "student_id": "19197",
        "photo_url": "photos/19197.jpg",
        "title": "เด็กหญิง",
        "firstname": "นภัสนันท์",
        "lastname": "เทพพงค์ชัย",
        "fullname": "เด็กหญิงนภัสนันท์ เทพพงค์ชัย",
        "fullname_en": "Naphatsanan Tappongchai",
        "nickname": "แอบเปิ้ล",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901630481",
        "birthdate": "16 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0803108518",
        "school_old": "โรงเรียนเทศบาลตำบลแม่คำ(แม่คำสบเปินราษฎร์นุกูล)",
        "gpa": "3.97",
        "dream": "เภสัชกร,หมอ",
        "guardian_name": "นาย โสฬส  เทพพงค์ชัย",
        "guardian_phone": "0842231839",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 15,
            "social": 14,
            "math_basic": 15,
            "thai": 13,
            "math_add1": 19,
            "math_add2": 5,
            "chinese": 18,
            "eng_basic": 14,
            "sci_basic": 16,
            "eng_rw": 13,
            "total_score": 142
        }
    },
    {
        "no": 30,
        "student_id": "19198",
        "photo_url": "photos/19198.jpg",
        "title": "เด็กหญิง",
        "firstname": "นวรัตน์",
        "lastname": "พูนชัย",
        "fullname": "เด็กหญิงนวรัตน์ พูนชัย",
        "fullname_en": "Nawarat Poonchai",
        "nickname": "ขนมหวาน",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901649033",
        "birthdate": "31 มีนาคม 2557",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0842207708",
        "school_old": "โรงเรียนอนุบาลเมืองเชียงราย(สันทรายราษฎร์ดรุณานุเคราะห์)",
        "gpa": "3.61",
        "dream": "สัตวแพทย์",
        "guardian_name": "นางสาว อัญชรี เรือนศรี",
        "guardian_phone": "0988745954",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 18,
            "social": 12,
            "math_basic": 13,
            "thai": 11,
            "math_add1": 9,
            "math_add2": 3,
            "chinese": 13,
            "eng_basic": 18,
            "sci_basic": 12,
            "eng_rw": 19,
            "total_score": 128
        }
    },
    {
        "no": 31,
        "student_id": "19199",
        "photo_url": "photos/19199.jpg",
        "title": "เด็กหญิง",
        "firstname": "นิชาภา",
        "lastname": "กันทะอินทร์",
        "fullname": "เด็กหญิงนิชาภา กันทะอินทร์",
        "fullname_en": "Nichapa Kantain",
        "nickname": "พราว",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901645992",
        "birthdate": "16 มีนาคม 2557",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0864317675",
        "school_old": "โรงเรียนราชประชานุเคราะห์ 15",
        "gpa": "3.85",
        "dream": "ทนาย",
        "guardian_name": "นางสาว วราพร โพธิชัยเลิศ",
        "guardian_phone": "0623539587",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 12,
            "social": 14,
            "math_basic": 13,
            "thai": 10,
            "math_add1": 10,
            "math_add2": 3,
            "chinese": 16,
            "eng_basic": 11,
            "sci_basic": 10,
            "eng_rw": 8,
            "total_score": 107
        }
    },
    {
        "no": 32,
        "student_id": "19200",
        "photo_url": "photos/19200.jpg",
        "title": "เด็กหญิง",
        "firstname": "เบญญาภา",
        "lastname": "ปันอินแปง",
        "fullname": "เด็กหญิงเบญญาภา ปันอินแปง",
        "fullname_en": "benyapa  paninpang",
        "nickname": "โฟกัส",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901617123",
        "birthdate": "2 ตุลาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0610816119",
        "school_old": "โรงเรียนเชียงรายวิทยาคม",
        "gpa": "3.58",
        "dream": "-",
        "guardian_name": "นาย นิธิพัฒน์ ปันอินแปง",
        "guardian_phone": "0819501497",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 9,
            "social": 10,
            "math_basic": 15,
            "thai": 9,
            "math_add1": 16,
            "math_add2": 4,
            "chinese": 17,
            "eng_basic": 9,
            "sci_basic": 14,
            "eng_rw": 7,
            "total_score": 110
        }
    },
    {
        "no": 33,
        "student_id": "19201",
        "photo_url": "photos/19201.jpg",
        "title": "เด็กหญิง",
        "firstname": "ประภัชณิชา",
        "lastname": "ยาปะโลหิต",
        "fullname": "เด็กหญิงประภัชณิชา ยาปะโลหิต",
        "fullname_en": "Phaphatchaneecha Yapalohit",
        "nickname": "ไคชิน",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901616011",
        "birthdate": "26 กันยายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0960076374",
        "school_old": "โรงเรียนอนุบาลเชียงราย",
        "gpa": "3.87",
        "dream": "ทันตแพทย์",
        "guardian_name": "นางสาว ชนัญชิดา อ่อนดาบ",
        "guardian_phone": "0614580388",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 16,
            "social": 14,
            "math_basic": 18,
            "thai": 12,
            "math_add1": 19,
            "math_add2": 4,
            "chinese": 18,
            "eng_basic": 15,
            "sci_basic": 15,
            "eng_rw": 14,
            "total_score": 145
        }
    },
    {
        "no": 34,
        "student_id": "19202",
        "photo_url": "photos/19202.jpg",
        "title": "เด็กหญิง",
        "firstname": "ปุณฑริกา",
        "lastname": "ตันแก้ว",
        "fullname": "เด็กหญิงปุณฑริกา ตันแก้ว",
        "fullname_en": "Puntarika Tankaew",
        "nickname": "สมาย",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901631240",
        "birthdate": "19 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0950706196",
        "school_old": "โรงเรียนอนุบาลแม่สาย(สายศิลปศาสตร์)",
        "gpa": "3.79",
        "dream": "นักฟุตบอลอาชีพ",
        "guardian_name": "นางสาว วิไลพร ตันแก้ว",
        "guardian_phone": "0806789092",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 14,
            "social": 10,
            "math_basic": 13,
            "thai": 9,
            "math_add1": 14,
            "math_add2": 2,
            "chinese": 14,
            "eng_basic": 15,
            "sci_basic": 6,
            "eng_rw": 9,
            "total_score": 106
        }
    },
    {
        "no": 35,
        "student_id": "19203",
        "photo_url": "photos/19203.jpg",
        "title": "เด็กหญิง",
        "firstname": "พัชรพร",
        "lastname": "ทองทิพย์",
        "fullname": "เด็กหญิงพัชรพร ทองทิพย์",
        "fullname_en": "Patcharaporn  Thongthip",
        "nickname": "ฝ้าย",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901621350",
        "birthdate": "22 ตุลาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0948943420",
        "school_old": "โรงเรียนเทศบาล 4 สันป่าก่อ",
        "gpa": "3.96",
        "dream": "นักบัญชี",
        "guardian_name": "นางสาว ปราณี ทองทิพย์",
        "guardian_phone": "0835810766",
        "relation": "ผู้ปกครอง",
        "duty_day": "ศุกร์",
        "study_group": "กลุ่ม C",
        "ls_status": "เด็กกลุ่มห่วงใย (LS)",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 15,
            "social": 13,
            "math_basic": 16,
            "thai": 15,
            "math_add1": 20,
            "math_add2": 4,
            "chinese": 14,
            "eng_basic": 15,
            "sci_basic": 13,
            "eng_rw": 13,
            "total_score": 138
        }
    },
    {
        "no": 36,
        "student_id": "19204",
        "photo_url": "photos/19204.jpg",
        "title": "เด็กหญิง",
        "firstname": "พิมพ์ชนก",
        "lastname": "พุทธสาร",
        "fullname": "เด็กหญิงพิมพ์ชนก พุทธสาร",
        "fullname_en": "Pimchanok Phutthasan",
        "nickname": "พิมมี่",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901630286",
        "birthdate": "13 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0928317032",
        "school_old": "โรงเรียนอนุบาลบ้านลูกรัก",
        "gpa": "3.01",
        "dream": "-",
        "guardian_name": "นางสาว พรลิขิต ซาวคำเขต",
        "guardian_phone": "0848060660",
        "relation": "ผู้ปกครอง",
        "duty_day": "จันทร์",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 15,
            "social": 13,
            "math_basic": 12,
            "thai": 10,
            "math_add1": 13,
            "math_add2": 3,
            "chinese": 17,
            "eng_basic": 15,
            "sci_basic": 13,
            "eng_rw": 11,
            "total_score": 122
        }
    },
    {
        "no": 37,
        "student_id": "19205",
        "photo_url": "photos/19205.jpg",
        "title": "เด็กหญิง",
        "firstname": "วรนุช",
        "lastname": "นามแสง",
        "fullname": "เด็กหญิงวรนุช นามแสง",
        "fullname_en": "woranut namsang",
        "nickname": "นุ่น",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "8577485000129",
        "birthdate": "11 กันยายน 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0660384761",
        "school_old": "โรงเรียนบ้านดู่(สหราษฎร์พัฒนาคาร)",
        "gpa": "3.77",
        "dream": "หมอ",
        "guardian_name": "นาย สาม นามแสง",
        "guardian_phone": "0988108863",
        "relation": "ผู้ปกครอง",
        "duty_day": "อังคาร",
        "study_group": "กลุ่ม B",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 7,
            "social": 14,
            "math_basic": 10,
            "thai": 12,
            "math_add1": 11,
            "math_add2": 3,
            "chinese": 19,
            "eng_basic": 7,
            "sci_basic": 13,
            "eng_rw": 5,
            "total_score": 101
        }
    },
    {
        "no": 38,
        "student_id": "19206",
        "photo_url": "photos/19206.jpg",
        "title": "เด็กหญิง",
        "firstname": "สุพรรษา",
        "lastname": "กิติ",
        "fullname": "เด็กหญิงสุพรรษา กิติ",
        "fullname_en": "Suphanasa Kitti",
        "nickname": "เเก้ม",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1579901603483",
        "birthdate": "20 กรกฎาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0825032546",
        "school_old": "โรงเรียนเทศบาล1ป่าก่อดำ",
        "gpa": "3.76",
        "dream": "เภสัชกร",
        "guardian_name": "นางสาว เบญจวรรณ ใจยะ",
        "guardian_phone": "0882894857",
        "relation": "ผู้ปกครอง",
        "duty_day": "พุธ",
        "study_group": "กลุ่ม C",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 8,
            "social": 12,
            "math_basic": 8,
            "thai": 9,
            "math_add1": 13,
            "math_add2": 2,
            "chinese": 9,
            "eng_basic": 8,
            "sci_basic": 9,
            "eng_rw": 5,
            "total_score": 83
        }
    },
    {
        "no": 39,
        "student_id": "19207",
        "photo_url": "photos/19207.jpg",
        "title": "เด็กหญิง",
        "firstname": "อังควิกา",
        "lastname": "กันทะนันท์",
        "fullname": "เด็กหญิงอังควิกา กันทะนันท์",
        "fullname_en": "Angkhawika Kanthanan",
        "nickname": "อัยย์วี่",
        "gender": "หญิง",
        "classroom": "ม.1.4 (SMT)",
        "national_id": "1577100000045",
        "birthdate": "11 ธันวาคม 2556",
        "religion": "ศาสนาพุทธ",
        "student_phone": "0931584687",
        "school_old": "โรงเรียนลูกรักเชียงของ",
        "gpa": "3.83",
        "dream": "ตำรวจหญิง",
        "guardian_name": "นางสาว อุศนา กันทะนันท์",
        "guardian_phone": "0931439378",
        "relation": "ผู้ปกครอง",
        "duty_day": "พฤหัสบดี",
        "study_group": "กลุ่ม A",
        "ls_status": "ทั่วไป",
        "notes": "ครูที่ปรึกษา: นางสาวพรรณนิภา มูลโมกข์ | ครู LS: นายปณิพัฒน์ อินทะชัย",
        "scores": {
            "eng_comm": 10,
            "social": 8,
            "math_basic": 7,
            "thai": 10,
            "math_add1": 10,
            "math_add2": 0,
            "chinese": 12,
            "eng_basic": 5,
            "sci_basic": 9,
            "eng_rw": 6,
            "total_score": 77
        }
    }
];